name: Cypress Tests
on: [push]
jobs: 
  cypress run:
    runs on: windows latest
    steps:
      - name: Checkout
        uses: actions/checkout@2.3.4
      - name: Cypress.io
        uses: cypress.io/gitupaction@2.9.7
        with:
          start: npm start
